### ISSUE TITLE
Error: division by 0 (error token is "0")

### ISSUE THREAD

**Issue by prashanthrajagopal** [mclarkson/check_diskstat#6]
Here is the error. Please let me know if you need any other info

./check_diskstat.sh -d xvda1 -W 10 -C 20
./check_diskstat.sh: line 218: let: BYTES_READ_PER_SEC = 8 * 512 / 0: division by 0 (error token is "0")
./check_diskstat.sh: line 219: let: BYTES_WRITTEN_PER_SEC = 128 * 512 / 0: division by 0 (error token is "0")
./check_diskstat.sh: line 220: let: TPS=(2571552 - 2571551 + 7014277 - 7014268) / 0: division by 0 (error token is "0")
./check_diskstat.sh: line 222: let: KBYTES_READ_PER_SEC =  / 1024: syntax error: operand expected (error token is "/ 1024")
./check_diskstat.sh: line 223: let: KBYTES_WRITTEN_PER_SEC =  / 1024: syntax error: operand expected (error token is "/ 1024")
./check_diskstat.sh: line 256: let: AQUSZ = ( 4 / 0 ) / 1000: division by 0 (error token is "0 ) / 1000")
./check_diskstat.sh: line 302: [: -gt: unary operator expected

**Comment by mclarkson** [comment]
Use 'xvda' instead. Stats for the whole disk. The OS doesn't save stats for partitions.

**Comment by prashanthrajagopal** [comment]
Sorry missed mentioning above, the error is intermittent. please refer below. 

```
root@vmn:~# ./check_diskstat.sh -d xvda1 -W 10 -C 20
summary: 0 io/s, read 0 sectors (0kB/s), write 0 sectors (0kB/s), queue size 0 in 2 seconds | tps=0io/s;;; read=0b/s;;; write=0b/s;;; avgrq-sz=0;;; avgqu-sz=0;10;20; await=0ms;;;
root@vmn:~# ./check_diskstat.sh -d xvda1 -W 10 -C 20
^[[A
summary: 20 io/s, read 0 sectors (0kB/s), write 504 sectors (126kB/s), queue size 0 in 2 seconds | tps=20io/s;;; read=0b/s;;; write=129024b/s;;; avgrq-sz=12;;; avgqu-sz=0;10;20; await=0ms;;;
root@vmn:~# ./check_diskstat.sh -d xvda1 -W 10 -C 20
./check_diskstat.sh: line 218: let: BYTES_READ_PER_SEC = 0 * 512 / 0: division by 0 (error token is "0")
./check_diskstat.sh: line 219: let: BYTES_WRITTEN_PER_SEC = 152 * 512 / 0: division by 0 (error token is "0")
./check_diskstat.sh: line 220: let: TPS=(3023138 - 3023138 + 10510492 - 10510482) / 0: division by 0 (error token is "0")
./check_diskstat.sh: line 222: let: KBYTES_READ_PER_SEC =  / 1024: syntax error: operand expected (error token is "/ 1024")
./check_diskstat.sh: line 223: let: KBYTES_WRITTEN_PER_SEC =  / 1024: syntax error: operand expected (error token is "/ 1024")
./check_diskstat.sh: line 256: let: AQUSZ = ( 0 / 0 ) / 1000: division by 0 (error token is "0 ) / 1000")
./check_diskstat.sh: line 302: [: -gt: unary operator expected
summary:  io/s, read 0 sectors (kB/s), write 152 sectors (kB/s), queue size  in 0 seconds | tps=io/s;;; read=b/s;;; write=b/s;;; avgrq-sz=15;;; avgqu-sz=;10;20; await=0ms;;;
```

```
root@vmn:~# disk -l

Disk /dev/xvda1: 600.2 GB, 600221679616 bytes
255 heads, 63 sectors/track, 72972 cylinders, total 1172307968 sectors
Units = sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disk identifier: 0x00000000
```

**Comment by mclarkson** [comment]
Thanks for that @prashanthrajagopal. I have added a check for time delta (time since previous check) of 0 seconds. The plugin has a minimum resolution of 1 second.
