### ISSUE TITLE
Is a Release appropriate?

### ISSUE THREAD

**Issue by nmacgreg** [mclarkson/check_diskstat#8]
If it's convenient for you, could you issue a Release, whenever you've got a stable version?  This is a pretty personal request, do what you want! (We manage our environment based on RPM's; we traditionally use automation to build new RPM's whenever a new Release is issued. )

**Comment by mclarkson** [comment]
Nice idea. I'll try to make releases. Do you publish the RPM somewhere so others can use it?

**Comment by nmacgreg** [comment]
I can't, since we don't have an external RPM repository... I'll discuss building one with my team.
I was going to offer my trivial .spec file, but then I found your work on nagarest, and realized you could probably whip up one, without my help.  I am *seriously* looking forward to playing with nagarest tomorrow, as it will fit nicely with our ansible infrastructure.
